-- 코드를 입력하세요
WITH CAR_FEE_INFO AS (
    SELECT C.CAR_ID, D.CAR_TYPE, ROUND(DAILY_FEE * 30 * (100 - DISCOUNT_RATE) / 100, 0) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
    ON C.CAR_TYPE = D.CAR_TYPE AND C.CAR_TYPE IN ('세단', 'SUV') AND D.DURATION_TYPE = '30일 이상'
)

SELECT DISTINCT F.CAR_ID, CAR_TYPE, FEE
FROM CAR_FEE_INFO F
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON F.CAR_ID = H.CAR_ID AND F.CAR_ID NOT IN (SELECT DISTINCT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE DATE_FORMAT(START_DATE, "%Y-%m") <= '2022-11' AND DATE_FORMAT(END_DATE, "%Y-%m") >= '2022-11')
WHERE FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;

# SELECT CAR_ID, START_DATE, END_DATE
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE CAR_ID IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE DATE_FORMAT(START_DATE, "%Y-%m") <= '2022-11' AND DATE_FORMAT(END_DATE, "%Y-%m") >= '2022-11')
# ORDER BY CAR_ID

# SELECT CAR_ID
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
# WHERE DATE_FORMAT(START_DATE, "%Y-%m") <= '2022-11' AND DATE_FORMAT(END_DATE, "%Y-%m") >= '2022-11'
# ORDER BY CAR_ID