-- 코드를 입력하세요
WITH HIGHEST_FAV AS (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)

SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES
FROM REST_INFO R
JOIN HIGHEST_FAV H
ON H.FOOD_TYPE = R.FOOD_TYPE
WHERE H.FAVORITES = R.FAVORITES
ORDER BY FOOD_TYPE DESC;

# SELECT *
# FROM HIGHEST_FAV
