-- 코드를 입력하세요
SELECT YEAR(O.SALES_DATE), MONTH(O.SALES_DATE), U.GENDER, COUNT(DISTINCT O.USER_ID) AS USERS
FROM ONLINE_SALE O
JOIN USER_INFO U ON O.USER_ID = U.USER_ID
GROUP BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE), U.GENDER
HAVING U.GENDER IS NOT NULL AND COUNT(U.GENDER) > 0
ORDER BY 1, 2, 3