-- 코드를 작성해주세요
WITH RECURSIVE ECOLI_GEN
AS (
    SELECT 1 AS GENERATION, ID AS ECOLI
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT GENERATION+1 AS NUM, D.ID AS C
    FROM ECOLI_GEN G
    JOIN ECOLI_DATA D
    ON G.ECOLI = D.PARENT_ID
    WHERE G.ECOLI IS NOT NULL
)


SELECT COUNT(*) AS COUNT, GENERATION
FROM ECOLI_GEN
WHERE ECOLI NOT IN (SELECT PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL) IS NOT FALSE
GROUP BY GENERATION
ORDER BY GENERATION