-- 코드를 입력하세요
WITH LAST_RENT AS (
    SELECT CAR_ID, START_DATE, END_DATE 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16'
    GROUP BY CAR_ID
    ORDER BY CAR_ID DESC
)

# SELECT *
# FROM LAST_RENT

SELECT DISTINCT CAR_ID, IF(CAR_ID IN (SELECT CAR_ID FROM LAST_RENT), '대여중', '대여 가능') AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
ORDER BY CAR_ID DESC;
