-- 코드를 입력하세요
WITH RECURSIVE FULL_HOURS AS (
    SELECT 0 AS hour
    UNION ALL
    SELECT hour + 1 FROM FULL_HOURS WHERE hour < 23
)

SELECT H.HOUR, COUNT(A.ANIMAL_ID) AS COUNT
FROM FULL_HOURS H
LEFT JOIN ANIMAL_OUTS A ON H.HOUR = HOUR(A.DATETIME)
GROUP BY H.HOUR
ORDER BY H.HOUR