-- 코드를 작성해주세요
SELECT T.ITEM_ID, (SELECT ITEM_NAME FROM ITEM_INFO I WHERE T.ITEM_ID = I.ITEM_ID) AS ITEM_NAME, (SELECT RARITY FROM ITEM_INFO I WHERE T.ITEM_ID = I.ITEM_ID) AS RARITY
FROM ITEM_INFO I
JOIN ITEM_TREE T
ON I.ITEM_ID = T.PARENT_ITEM_ID
WHERE I.RARITY = 'RARE'
ORDER BY T.ITEM_ID DESC