-- 코드를 작성해주세요
# SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) - SIZE_OF_COLONY AS YEAR_DEV, ID
# FROM ECOLI_DATA
# GROUP BY YEAR(DIFFERENTIATION_DATE)

SELECT YEAR(A.DIFFERENTIATION_DATE) AS YEAR, (SELECT MAX(SIZE_OF_COLONY) FROM ECOLI_DATA D WHERE YEAR(A.DIFFERENTIATION_DATE) = YEAR(D.DIFFERENTIATION_DATE) GROUP BY YEAR(DIFFERENTIATION_DATE)) - SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA A
ORDER BY YEAR, SIZE_OF_COLONY DESC;